- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install httpd package on all application servers
      yum:
        name: httpd
        state: installed
    - name: Create a file and Add a line to a file
      lineinfile:
        path: /var/www/html/index.html
        line: "This is a Nautilus sample file, created using Ansible!"
        create: yes
        insertbefore: BOF
        owner: apache
        group: apache
        mode: 0644
    - name: Add a line to a file
      lineinfile:
        path: /var/www/html/index.html
        insertbefore: BOF
        line: 'Welcome to xFusionCorp Industries!'
    - name: Start httpd service
      service:
        name: httpd
        state: restarted
        enabled: true
